### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [demianmian/PY202309#3]
### 없는 PDF 파일
- project/week8/search_engine.pdf
	- 위 파일 이름이나 위치를 다시 확인하세요. 보고서 채점이 수행되지 않습니다.

### 에러 있음. 아래 파일/에러메세지/솔루션을 확인하세요
- ERROR in practice/week3/basic
    - unmatched ')' (<unknown>, line 114)
        - 마지막 괄호가 추가되어 코드가 실행되지 않습니다. 괄호를 제거해주세요. 

### 기능/코드 대비 주석이 부족합니다. 주석을 추가하거나 쪼개세요.
- Insufficient comments in challenge/week4/condition
- Insufficient comments in practice/week3/basic
- Insufficient comments in practice/week5/turtle
    - 추출된 주석: #   5 0 까 지   터 틀   반 지 름   값 에   따 라   색 깔 을   바 꿔 주 는   코 드

**Comment by demianmian** [comment]
다 완료했습니다!
